export const publicationData = [
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  },
  {
    title: "The Clnephile",
    sponsored: "yes",
    doFollow: "no",
    indexed: "yes",
    region: "United State",
    da: "95",
    dr: "95",
    ttp: "1-3 days",
    amount: "500"
  }
]