const formatCurrency = (amount) => {
  // Ensure the amount is a number before formatting
  const numericAmount = parseFloat(amount);
  if (isNaN(numericAmount)) return '$0.00';
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(numericAmount);
};



/**
 * Main Invoice Component - Renders the invoice using provided data.
 */
const Invoice = ({ data, ref }) => {
  // Calculate totals
  const subtotal = data.items.reduce((sum, item) => sum + (item.quantity * item.unitPrice), 0);
  const taxAmount = subtotal * (data.taxRate / 100);
  const totalDue = subtotal + taxAmount;

  // Determine status styling
  let statusClass = 'text-red-600';
  if (data.paymentStatus.toUpperCase() === 'PAID') {
    statusClass = 'text-green-600';
  } else if (data.paymentStatus.toUpperCase() === 'PENDING') {
    statusClass = 'text-orange-600';
  }

  return (
    <div ref={ref} id="invoice-content" className="bg-white p-4 sm:p-10 rounded-xl shadow-2xl max-w-4xl mx-auto">

      {/* Header Section */}
      <header className="flex justify-between items-start pb-6 border-b border-gray-200">
        <div>
          <h2 className="text-4xl font-extrabold text-indigo-700">INVOICE</h2>
          <p className="text-sm text-gray-500">#{data.id}</p>
        </div>
        <div className="text-right">
          <p className="font-semibold text-gray-800">{data.company.name}</p>
          <p className="text-sm text-gray-600">{data.company.address}</p>
          <p className="text-sm text-gray-600">{data.company.email}</p>
        </div>
      </header>

      {/* Billing & Date Section */}
      <section className="flex justify-between mt-8 mb-10 text-sm">
        <div>
          <h3 className="font-bold text-gray-700 uppercase mb-2">Bill To:</h3>
          <p className="font-semibold text-gray-800">{data.client.name}</p>
          <p className="text-gray-600">{data.client.address}</p>
          <p className="text-gray-600">{data.client.email}</p>
        </div>
        <div className="text-right space-y-1">
          <p><span className="font-semibold text-gray-700">Issue Date:</span> {data.issueDate}</p>
          <p><span className="font-semibold text-gray-700">Due Date:</span> {data.dueDate}</p>
          <p><span className="font-semibold text-gray-700">Status:</span> <span className={`${statusClass} font-bold`}>{data.paymentStatus.toUpperCase()}</span></p>
        </div>
      </section>

      {/* Items Table */}
      <section>
        <div className="bg-indigo-50 rounded-t-lg">
          <div className="grid grid-cols-12 py-3 px-4 text-xs font-bold text-indigo-700 uppercase">
            <div className="col-span-6">Description</div>
            <div className="col-span-2 text-right">Qty</div>
            <div className="col-span-2 text-right">Unit Price</div>
            <div className="col-span-2 text-right">Amount</div>
          </div>
        </div>
        <div className="border-b border-gray-200">
          {data.items.map((item, index) => <div key={index} className="invoice-item-row grid grid-cols-12 py-3 px-4 border-t border-gray-100 text-sm hover:bg-gray-50 break-inside-avoid">
            <div className="col-span-6 font-medium text-gray-800">{item.description}</div>
            <div className="col-span-2 text-right text-gray-600">{item.quantity}</div>
            <div className="col-span-2 text-right text-gray-600">{formatCurrency(item.unitPrice)}</div>
            <div className="col-span-2 text-right font-semibold text-gray-800">{formatCurrency(item.quantity * item.unitPrice)}</div>
          </div>)}
        </div>
      </section>

      {/* Totals Section */}
      <section className="flex justify-end mt-6">
        <div className="w-full max-w-xs space-y-3 text-sm">
          <div className="flex justify-between font-medium text-gray-700">
            <span>Subtotal:</span>
            <span className="font-semibold">{formatCurrency(subtotal)}</span>
          </div>
          <div className="flex justify-between font-medium text-gray-700 border-t pt-3">
            <span>Tax ({data.taxRate}%):</span>
            <span className="font-semibold">{formatCurrency(taxAmount)}</span>
          </div>
          <div className="flex justify-between font-bold text-2xl py-3 border-t-2 border-indigo-600 mt-4">
            <span>Total Due:</span>
            <span className="text-indigo-700">{formatCurrency(totalDue)}</span>
          </div>
        </div>
      </section>

      {/* Notes and Footer */}
      <footer className="mt-12 pt-6 border-t border-gray-200 text-center text-xs text-gray-500">
        <p className="mb-2"><span className="font-semibold text-gray-700">Notes:</span> {data.notes}</p>
        <p>Generated by React Solutions Co. - Thank you for your continued partnership.</p>
      </footer>
    </div>
  );
};

export default Invoice;